### ISSUE TITLE
New Spoogler form prototype.

### ISSUE THREAD

**Issue by LightFelicis** [googleinterns/step236-2020#1]
Create a form containing textfields for:
-- Validity of partner's google account
-- Name of partner
-- Mail of partner (if they are Googlers)
-- [EDIT] Start date (if they are Nooglers)
Framework for React we decided to use is Material-UI.
Colors palette: https://coolors.co/e63946-ffffff-a8dadc-457b9d-1d3557

**Comment by LightFelicis** [comment]
![image](https://user-images.githubusercontent.com/21277176/90632937-7c949100-e225-11ea-8aee-1d1c71d8cbb0.png)

**Comment by xmxwx** [comment]
> Create a form containing textfields for:
> -- Validity of partner's google account
> -- Name of partner
> -- Mail of partner (if they are Googlers)

This is less than described in the DD. Is it WAI (i.e. will the rest be provided outside of the scope of the prototype?).

**Comment by LightFelicis** [comment]
The rest (personal data of Spoogler) is not in the form. It's in the id_token of currently logged in person.

**Comment by xmxwx** [comment]
What about the starting date in the Noogler case?

**Comment by LightFelicis** [comment]
It's something that admin will receive from HR (if we decide to validate starting date), right?. Including date field may cause problems -- if spoogler misclicks one day after the actual start date or contract will be postponed because of visa issues, should we allow them to view mailing list? Should we delete them from group? 

We can add the starting date and treat it as a second authentication factor.
If we don't authenticate the starting date, then there won't be any use of this field in form.

Is there any specific reason we want starting date to be provided by Spoogler and not by HR?

**Comment by xmxwx** [comment]
> It's something that admin will receive from HR (if we decide to validate starting date), right?. Including date field may cause problems -- if spoogler misclicks one day after the actual start date or contract will be postponed because of the visa issues, should we allow them to view the mailing list? Should we delete them from the group?

Issues like this are too nuanced to be usefully captured in software, therefore we leave the checking and the final decision to the admins.

> Is there any specific reason we want starting date to be provided by Spoogler and not by HR?

If the staring date is not provided by Spoogler, then it cannot be checked. What would the admin be checking if HR was telling the admin what's the given Googler's starting date?
